// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dkfnncpeaaxqarzrzkkq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrZm5uY3BlYWF4cWFyenJ6a2txIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk5MzA0NjUsImV4cCI6MjA3NTUwNjQ2NX0.Kv88GS63Fl_E9lEnJPMOo9OU-bBitXsFXDI9LCLyYtc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});